import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navbar
    nav_home: 'Home', nav_services: 'Services', nav_gallery: 'Gallery',
    nav_shop: 'Shop', nav_about: 'About', nav_contact: 'Contact',
    nav_book: 'Book Now', nav_book_full: 'Book Appointment',
    nav_location_label: 'Location', nav_hours_label: 'Hours', nav_hours: 'Mon–Sat 9AM–8PM',

    // Home Hero
    hero_eyebrow: 'Luxury Beauty & Med Spa — Cotonou',
    hero_title_1: 'Elevate',
    hero_title_2: 'Your Beauty',
    hero_sub: 'Transformative beauty rituals designed for the modern sovereign. Where artistry meets science.',
    hero_cta1: 'Book Appointment',
    hero_cta2: 'Explore Services',
    hero_scroll: 'Scroll',
    hero_stat1_num: '2,400+', hero_stat1_label: 'Transformations',
    hero_stat2_num: '98%', hero_stat2_label: 'Client Satisfaction',
    hero_stat3_num: '12+', hero_stat3_label: 'Years of Mastery',

    // Home CTA section
    home_cta_eyebrow: 'Begin Your Journey',
    home_cta_title1: 'You Deserve',
    home_cta_title2: 'Extraordinary',
    home_cta_sub: 'Book your private consultation today. Our specialists are ready to craft your signature transformation.',
    home_cta_btn: 'Reserve Your Session',

    // Services Overview (home component)
    so_eyebrow: 'Our Expertise',
    so_title: 'Signature',
    so_title_italic: 'Services',
    so_view_all: 'View All Services →',
    so_s1_title: 'Hair Extensions', so_s1_sub: 'Tape-In, Sew-In, Fusion',
    so_s2_title: 'Keratin Treatments', so_s2_sub: 'Brazilian, Express, Deep Care',
    so_s3_title: 'Med Spa Facials', so_s3_sub: 'HydraFacial, Chemical Peel',
    so_s4_title: 'Botox & Fillers', so_s4_sub: 'Lip, Cheek, Anti-Aging',
    so_s5_title: 'Lash & Brow', so_s5_sub: 'Extensions, Lamination, Tint',
    so_s6_title: 'Body Treatments', so_s6_sub: 'Sculpting, Wraps, Massage',

    // Signature Treatments (home component)
    st_eyebrow: 'Exclusive to Wendy Beauty',
    st_title: 'Signature',
    st_title_italic: 'Treatments',
    st_tag: 'Signature Treatment',
    st_book_btn: 'Book This Treatment',
    st_t1_title: 'The Golden Glow Facial',
    st_t1_desc: 'A 90-minute ritual combining 24k gold micro-infusion, diamond-tipped microdermabrasion, and LED light therapy. The pinnacle of skincare luxury.',
    st_t1_price: 'From $380', st_t1_duration: '90 min',
    st_t2_title: 'Obsidian Silk Extensions',
    st_t2_desc: 'Our flagship hair extension service. Hand-selected Remy hair in a seamless fusion application that lasts up to 6 months. Undetectable, lustrous, and transformative.',
    st_t2_price: 'From $600', st_t2_duration: '3–4 hours',
    st_t3_title: 'Sovereign Sculpt Body',
    st_t3_desc: 'A full-body contouring treatment combining radiofrequency, lymphatic drainage, and signature hot stone therapy. Redefine your silhouette.',
    st_t3_price: 'From $450', st_t3_duration: '120 min',

    // Gallery Teaser (home component)
    gt_eyebrow: 'Client Transformations',
    gt_title: 'The Gallery',
    gt_view_all: 'View Full Gallery →',
    gt_client_work: 'Client Work',

    // Testimonials (home component)
    tst_eyebrow: 'Client Voices',
    tst_title: 'Words of',
    tst_title_italic: 'Devotion',

    // Services Page
    svc_eyebrow: 'What We Offer',
    svc_title: 'Our',
    svc_title_italic: 'Services',
    svc_cta_title: 'Ready to Begin?',
    svc_cta_sub: 'Book your private consultation and let us craft your signature transformation.',
    svc_cta_btn: 'Reserve Your Session',
    // Service category titles
    svc_cat1: 'Hair Extensions',
    svc_cat2: 'Hair Treatments',
    svc_cat3: 'Botox & Injectables',
    svc_cat4: 'Facial & Skin Treatments',
    svc_cat5: 'Body Sculpting & Wellness',
    svc_cat6: 'Beauty & Lash',
    // Service names & descriptions
    svc_s1_name: 'Tape-In Extensions', svc_s1_desc: 'Seamless, reusable, and the most natural-looking method. Applied in under 90 minutes.',
    svc_s2_name: 'Sew-In / Weave', svc_s2_desc: 'The gold standard for volume and length. Fully customizable track pattern for maximum style versatility.',
    svc_s3_name: 'Keratin Fusion Bonds', svc_s3_desc: 'The most permanent and natural option. Individual bonds applied with signature keratin protein.',
    svc_s4_name: 'Halo Extensions', svc_s4_desc: 'Zero damage, instant transformation. Perfect for those new to extensions.',
    svc_s5_name: 'Brazilian Keratin', svc_s5_desc: 'Eliminate frizz and add luminous shine for up to 6 months. Heat-activated keratin complex.',
    svc_s6_name: 'Japanese Straightening', svc_s6_desc: "Permanent restructuring of the hair's disulfide bonds. Silky-straight results that grow out beautifully.",
    svc_s7_name: 'Olaplex Restoration', svc_s7_desc: 'A science-backed protein treatment that rebuilds broken bonds from the inside out.',
    svc_s8_name: 'Scalp Rejuvenation', svc_s8_desc: 'A clinical treatment targeting follicle health, featuring peptide infusion and LED therapy.',
    svc_s9_name: 'Botox', svc_s9_desc: 'Precision neurotoxin placement by our board-certified aesthetic specialist to smooth fine lines and restore youthful expression. Natural-looking results, never frozen.',
    svc_s10_name: 'Lip Fillers', svc_s10_desc: 'Hyaluronic acid filler for fuller, symmetrically defined lips. We specialise in the "natural plump" — volume that looks born, not injected.',
    svc_s11_name: 'Smile Line Fillers', svc_s11_desc: 'Nasolabial fold and marionette line correction using premium HA filler. Softens deep lines while maintaining natural facial movement.',
    svc_s12_name: 'PDO Thread Nose Lift', svc_s12_desc: 'A non-surgical rhinoplasty alternative using polydioxanone threads to lift, refine, and define the nasal tip and bridge. Zero downtime.',
    svc_s13_name: 'Butt Fillers', svc_s13_desc: 'Non-surgical gluteal enhancement using bio-stimulating fillers. Adds subtle volume and lift without the risks of surgical augmentation.',
    svc_s14_name: 'Sweating Treatment (Botox)', svc_s14_desc: 'Hyperhidrosis treatment using micro-injections of botulinum toxin to the underarms, palms, or feet. Clinically proven to reduce excessive sweating by up to 87%.',
    svc_s15_name: 'Golden Glow Facial', svc_s15_desc: '24k gold micro-infusion + diamond microdermabrasion + LED. Our signature luxury facial for an unmatched radiance.',
    svc_s16_name: 'HydraFacial MD', svc_s16_desc: 'The 6-step medical-grade hydrafacial with customized vortex fusion serums for deep cleanse, extraction, and hydration.',
    svc_s17_name: 'Facial Treatments', svc_s17_desc: "A curated menu of targeted facials including deep-cleanse, anti-aging, brightening, and sensitive-skin protocols. Each treatment is fully customized to your skin's needs on the day.",
    svc_s18_name: 'Skin Rejuvenation Treatments', svc_s18_desc: 'Advanced skin renewal using a combination of chemical peels, micro-needling, and PRP therapy. Dramatically improves texture, tone, and luminosity.',
    svc_s19_name: 'Skincare Treatments', svc_s19_desc: 'Medical-grade skincare protocols targeting acne, hyperpigmentation, rosacea, and premature aging. Includes LED phototherapy, enzyme treatments, and bespoke serums.',
    svc_s20_name: 'Body Contouring & Sculpting', svc_s20_desc: 'Non-invasive body reshaping using radiofrequency, ultrasound cavitation, and EMS muscle stimulation. Targets stubborn fat deposits and tightens loose skin for a visibly sculpted silhouette.',
    svc_s21_name: 'Fat Removal / Fat Dissolving', svc_s21_desc: 'Aqualyx or Kybella injections to permanently dissolve localised fat cells in the chin, jowls, abdomen, thighs, and arms. A clinically proven alternative to liposuction.',
    svc_s22_name: 'IV Infusions', svc_s22_desc: 'Bespoke intravenous drip therapy delivering vitamins, minerals, antioxidants, and hydration directly into the bloodstream. Protocols include Glow, Immunity, Energy, Hangover Recovery, and Anti-Aging blends.',
    svc_s23_name: 'Massage Therapy', svc_s23_desc: "Therapeutic massage tailored to your body's needs, from deep-tissue sports massage to a relaxing Swedish session. All treatments use our signature cold-pressed argan and jasmine oil blend.",
    svc_s24_name: 'Hot Stone Massage', svc_s24_desc: 'Volcanic basalt stones heated to the perfect temperature, combined with CBD-infused argan oil for profound muscle release and deep relaxation.',
    svc_s25_name: 'Body Wrap', svc_s25_desc: 'Detoxifying seaweed and mineral wrap with an exfoliating body scrub. Draws out impurities, boosts circulation, and leaves skin immaculately soft.',
    svc_s26_name: 'Lash Extensions', svc_s26_desc: 'Individually applied silk, mink, or volume lashes customised to your eye shape and desired drama level. Classic, hybrid, and mega-volume sets available.',
    svc_s27_name: 'Waxing', svc_s27_desc: 'Full-body waxing using our warm honey-resin formula, gentle enough for sensitive skin. Services include brow shaping, lip, underarm, Brazilian, and full-leg.',
    svc_s28_name: 'Beauty Consultations', svc_s28_desc: 'A private 45-minute session with one of our senior specialists to map your complete beauty journey. Complimentary with any service booking.',
    svc_cat7: 'Injectables & Aesthetic Treatments',
    svc_s29_name: 'Skin Brightening & Hyperpigmentation Treatment', svc_s29_desc: 'Advanced depigmentation protocol targeting dark spots, uneven skin tone and melasma. Combines brightening serums, chemical agents and LED therapy for a visibly luminous, even complexion.',
    svc_s30_name: 'Russian Lip Filler', svc_s30_desc: "The iconic Russian technique using hyaluronic acid filler to create a defined cupid's bow, lifted lip corners and natural projection — without overfilling. Ideal for a pillowy, doe-eyed result.",
    svc_s31_name: 'Profile Balancing — Cheeks · Chin · Lips', svc_s31_desc: 'A comprehensive facial harmony treatment using strategic dermal filler placement across cheekbones, chin and lips. Restores facial symmetry and enhances natural bone structure for a sculpted, balanced profile.',
    svc_s32_name: 'Anti-Wrinkle Injections (Botox)', svc_s32_desc: "Precision neuromodulator injections to smooth crow's feet, forehead lines and frown lines. Our specialist uses micro-dosing techniques for natural, refreshed results — never frozen.",
    svc_s33_name: 'Nasolabial Folds Filler', svc_s33_desc: 'Targeted hyaluronic acid filler to soften the lines running from the nose to the corners of the mouth. Restores facial volume and smooths deep folds for a youthful, rested appearance.',

    // Shop Page
    shop_eyebrow: 'The Boutique',
    shop_title1: 'Shop', shop_title2: 'Premium',
    shop_sub: 'Curated luxury beauty essentials, available exclusively at Wendy Beauty.',
    shop_bag: 'Bag',
    shop_quick_add: 'Quick Add',
    shop_cat_all: 'All',

    // Gallery Page
    gal_eyebrow: 'Client Transformations',
    gal_title1: 'The', gal_title2: 'Gallery',
    gal_sub: 'Every image tells a story of transformation. Real clients, extraordinary results.',
    gal_before: 'Before', gal_after: 'After',

    // Booking Page
    bk_eyebrow: 'Concierge Booking',
    bk_title: 'Reserve Your', bk_title_italic: 'Session',
    bk_step0: 'Service', bk_step1: 'Specialist', bk_step2: 'Date & Time', bk_step3: 'Details', bk_step4: 'Confirm',
    bk_choose_service: 'Choose Your Service',
    bk_choose_specialist: 'Select Your Specialist',
    bk_choose_datetime: 'Choose Date & Time',
    bk_select_date: 'Select Date',
    bk_available_times: 'Available Times',
    bk_your_details: 'Your Details',
    bk_review: 'Review & Confirm',
    bk_back: 'Back', bk_continue: 'Continue', bk_confirm_btn: 'Confirm Booking',
    bk_your_selection: 'Your Selection',
    bk_label_service: 'Service', bk_label_specialist: 'Specialist',
    bk_label_date: 'Date', bk_label_time: 'Time', bk_label_duration: 'Duration',
    bk_label_client: 'Client', bk_label_contact: 'Contact', bk_label_total: 'Total',
    bk_deposit_note: 'A $50 deposit may be required to secure your appointment. Full payment due at service time.',
    bk_journey_note: 'Your journey begins with a service selection.',
    bk_confirmed_title: 'Confirmed',
    bk_confirmed_sub: 'Your appointment has been reserved. A confirmation has been sent to',
    bk_confirmed_sub2: 'We look forward to welcoming you.',
    bk_summary: 'Appointment Summary', bk_investment: 'Investment',
    bk_return_home: 'Return Home',
    bk_field_name: 'Full Name', bk_field_email: 'Email Address', bk_field_phone: 'Phone Number',
    bk_field_requests: 'Special Requests',
    bk_ph_name: 'Your full name', bk_ph_email: 'your@email.com', bk_ph_phone: '+229 000 000 000',
    bk_ph_requests: 'Any allergies, preferences, or special requests...',
    bk_svc_hair: 'Hair', bk_svc_medspa: 'Med Spa', bk_svc_body: 'Body', bk_svc_bridal: 'Bridal', bk_svc_lash: 'Lash & Brow',
    bk_svc_s1: 'Obsidian Silk Extensions', bk_svc_s2: 'Keratin Transformation',
    bk_svc_s3: 'Golden Glow Facial', bk_svc_s4: 'Botox & Filler Consult',
    bk_svc_s5: 'Sovereign Sculpt Body', bk_svc_s6: 'Bridal Package',
    bk_svc_s7: 'Lash Extension Full Set', bk_svc_s8: 'Precision Cut & Style',
    bk_svc_d1: '3–4 hours', bk_svc_d2: '2.5 hours', bk_svc_d3: '90 min',
    bk_svc_d4: '45 min', bk_svc_d5: '120 min', bk_svc_d6: '5 hours',
    bk_svc_d7: '2 hours', bk_svc_d8: '1 hour',
    bk_sp1_name: 'Wendy Beaumont', bk_sp1_role: 'Founder & Master Stylist', bk_sp1_spec: 'Extensions & Color',
    bk_sp2_name: 'Isabelle Chen', bk_sp2_role: 'Senior Colorist', bk_sp2_spec: 'Balayage & Keratin',
    bk_sp3_name: 'Maya Torres', bk_sp3_role: 'Med Spa Specialist', bk_sp3_spec: 'Facials & Injectables',
    bk_sp4_name: 'Priya Shah', bk_sp4_role: 'Body Sculptor', bk_sp4_spec: 'Body Treatments & Massage',

    // About Page
    ab_eyebrow: 'Our Story',
    ab_title: 'Born from a', ab_title_italic: 'Vision',
    ab_p1: 'Wendy Beauty Med Spa was founded on a radical belief: that every person who walks through our doors deserves to feel like the most extraordinary version of themselves.',
    ab_p2: 'In 2011, Wendy Beaumont returned from Paris with a collection of techniques, a philosophy of sovereign beauty, and a dream. Today, Wendy Beauty has performed over 2,400 transformations and earned a reputation as the destination for those who demand only the finest.',
    ab_cta: 'Book a Consultation',
    ab_val_eyebrow: 'What We Stand For',
    ab_val_title: 'Our', ab_val_title_italic: 'Philosophy',
    ab_v1_title: 'Mastery', ab_v1_desc: 'Every technician undergoes 300+ hours of advanced training before touching a single client. We accept nothing less than excellence.',
    ab_v2_title: 'Discretion', ab_v2_desc: 'Our clientele includes some of the world\'s most recognizable faces. Privacy is not a service — it is a sacred promise.',
    ab_v3_title: 'Integrity', ab_v3_desc: 'We will never recommend a service you don\'t need. Our consultations are honest, comprehensive, and your interests first.',
    ab_v4_title: 'Innovation', ab_v4_desc: 'We curate only the most advanced techniques and products from global markets. You receive tomorrow\'s treatments today.',
    ab_stat1_num: '2,400+', ab_stat1_label: 'Transformations',
    ab_stat2_num: '15+', ab_stat2_label: 'Years of Mastery',
    ab_stat3_num: '98%', ab_stat3_label: 'Client Retention',

    // Contact Page
    contact_eyebrow: 'Get in Touch',
    contact_title: 'Contact', contact_title2: 'Us',
    contact_sub: "We'd love to hear from you. Reach us by form, phone, or visit us in Cotonou.",
    contact_send_title: 'Send a Message',
    contact_send_btn: 'Send Message',
    contact_name_label: 'Full Name', contact_email_label: 'Email Address',
    contact_subject_label: 'Subject', contact_message_label: 'Message',
    contact_name_ph: 'Your name', contact_email_ph: 'your@email.com',
    contact_subject_ph: 'How can we help?', contact_message_ph: 'Tell us about your beauty goals...',
    contact_received_title: 'Message Received',
    contact_received_sub: 'Thank you for reaching out. A member of our team will be in touch within 24 hours.',
    contact_find_us: 'Find Us',
    contact_addr_label: 'Address', contact_phone_label: 'Phone',
    contact_email_info_label: 'Email', contact_hours_label: 'Hours',
    contact_addr_val: 'Hotel Mavilla, Lomnava\nCiné Concorde, Cotonou',
    contact_hours_val: 'Mon–Sat: 9AM – 8PM\nSun: By Appointment',
    contact_follow: 'Follow the Journey',

    // Footer
    footer_desc: 'Where elegance meets transformation. Luxury beauty services in Hotel Mavilla, Lomnava, Ciné Concorde, Cotonou.',
    footer_newsletter: 'Join the Inner Circle',
    footer_welcome: 'Welcome to the sanctuary.',
    footer_rights: '© 2026 WENDY BEAUTY MED SPA. ALL RIGHTS RESERVED.',
    footer_location: 'HOTEL MAVILLA, COTONOU, BENIN',
    footer_link_services: 'Services', footer_link_gallery: 'Gallery', footer_link_shop: 'Shop',
    footer_link_about: 'About', footer_link_booking: 'Booking', footer_link_contact: 'Contact',
    footer_link_privacy: 'Privacy', footer_link_terms: 'Terms',

    // Cart Sidebar
    cart_title: 'Your Bag', cart_empty: 'Your bag is empty.',
    cart_checkout: 'Checkout', cart_continue: 'Continue Shopping',
    cart_total: 'Total',

    // Product Modal
    pm_add_btn: 'Add to Bag',
    pm_color: 'Color', pm_weight: 'Weight', pm_rating: 'Rating',
  },
  fr: {
    // Navbar
    nav_home: 'Accueil', nav_services: 'Services', nav_gallery: 'Galerie',
    nav_shop: 'Boutique', nav_about: 'À Propos', nav_contact: 'Contact',
    nav_book: 'Réserver', nav_book_full: 'Prendre Rendez-vous',
    nav_location_label: 'Adresse', nav_hours_label: 'Horaires', nav_hours: 'Lun–Sam 9h–20h',

    // Home Hero
    hero_eyebrow: 'Beauté de Luxe & Med Spa — Cotonou',
    hero_title_1: 'Sublimez',
    hero_title_2: 'Votre Beauté',
    hero_sub: 'Des rituels beauté transformateurs conçus pour la souveraine moderne. Là où l\'art rencontre la science.',
    hero_cta1: 'Prendre Rendez-vous',
    hero_cta2: 'Découvrir les Services',
    hero_scroll: 'Défiler',
    hero_stat1_num: '2 400+', hero_stat1_label: 'Transformations',
    hero_stat2_num: '98%', hero_stat2_label: 'Satisfaction Clients',
    hero_stat3_num: '12+', hero_stat3_label: "Ans d'Excellence",

    // Home CTA section
    home_cta_eyebrow: 'Commencez Votre Voyage',
    home_cta_title1: 'Vous Méritez',
    home_cta_title2: "L'Extraordinaire",
    home_cta_sub: 'Réservez votre consultation privée dès aujourd\'hui. Nos spécialistes sont prêts à créer votre transformation signature.',
    home_cta_btn: 'Réserver Ma Séance',

    // Services Overview (home)
    so_eyebrow: 'Notre Expertise',
    so_title: 'Services',
    so_title_italic: 'Signature',
    so_view_all: 'Voir Tous les Services →',
    so_s1_title: 'Extensions Capillaires', so_s1_sub: 'Tape-In, Tissage, Fusion',
    so_s2_title: 'Traitements Kératine', so_s2_sub: 'Brésilien, Express, Soin Profond',
    so_s3_title: 'Soins Visage Med Spa', so_s3_sub: 'HydraFacial, Peeling Chimique',
    so_s4_title: 'Botox & Fillers', so_s4_sub: 'Lèvres, Joues, Anti-Âge',
    so_s5_title: 'Cils & Sourcils', so_s5_sub: 'Extensions, Lamination, Teinture',
    so_s6_title: 'Soins Corps', so_s6_sub: 'Sculpture, Enveloppements, Massage',

    // Signature Treatments (home)
    st_eyebrow: 'Exclusif à Wendy Beauty',
    st_title: 'Soins',
    st_title_italic: 'Signature',
    st_tag: 'Soin Signature',
    st_book_btn: 'Réserver ce Soin',
    st_t1_title: 'Le Facial Golden Glow',
    st_t1_desc: 'Un rituel de 90 minutes alliant micro-infusion à l\'or 24k, microdermabrasion à pointe de diamant et luminothérapie LED. Le summum du luxe skincare.',
    st_t1_price: 'À partir de 380$', st_t1_duration: '90 min',
    st_t2_title: 'Extensions Obsidian Silk',
    st_t2_desc: 'Notre service phare d\'extensions capillaires. Cheveux Remy sélectionnés à la main, en application fusion transparente qui dure jusqu\'à 6 mois. Indétectable, lustré et transformateur.',
    st_t2_price: 'À partir de 600$', st_t2_duration: '3–4 heures',
    st_t3_title: 'Sculpture Corporelle Sovereign',
    st_t3_desc: 'Un soin sculptant corps complet combinant radiofréquence, drainage lymphatique et pierres chaudes signature. Redéfinissez votre silhouette.',
    st_t3_price: 'À partir de 450$', st_t3_duration: '120 min',

    // Gallery Teaser (home)
    gt_eyebrow: 'Transformations Clients',
    gt_title: 'La Galerie',
    gt_view_all: 'Voir la Galerie Complète →',
    gt_client_work: 'Travail Client',

    // Testimonials (home)
    tst_eyebrow: 'Voix de nos Clientes',
    tst_title: 'Mots de',
    tst_title_italic: 'Dévotion',

    // Services Page
    svc_eyebrow: 'Ce Que Nous Offrons',
    svc_title: 'Nos',
    svc_title_italic: 'Services',
    svc_cta_title: 'Prête à Commencer ?',
    svc_cta_sub: 'Réservez votre consultation privée et laissez-nous créer votre transformation signature.',
    svc_cta_btn: 'Réserver Ma Séance',
    svc_cat1: 'Extensions Capillaires',
    svc_cat2: 'Traitements Capillaires',
    svc_cat3: 'Botox & Injectables',
    svc_cat4: 'Soins Visage & Peau',
    svc_cat5: 'Sculpture Corporelle & Bien-être',
    svc_cat6: 'Beauté & Cils',
    svc_s1_name: 'Extensions Tape-In', svc_s1_desc: 'Méthode la plus naturelle, réutilisable et sans couture. Application en moins de 90 minutes.',
    svc_s2_name: 'Tissage / Weave', svc_s2_desc: 'La référence pour le volume et la longueur. Patron de tracks entièrement personnalisable pour un style polyvalent.',
    svc_s3_name: 'Bonds Fusion Kératine', svc_s3_desc: 'L\'option la plus permanente et naturelle. Bonds individuels appliqués avec notre protéine kératine signature.',
    svc_s4_name: 'Extensions Halo', svc_s4_desc: 'Zéro dommage, transformation instantanée. Parfait pour celles qui découvrent les extensions.',
    svc_s5_name: 'Kératine Brésilienne', svc_s5_desc: 'Éliminez les frisottis et ajoutez un éclat lumineux pour jusqu\'à 6 mois. Complexe kératine activé par la chaleur.',
    svc_s6_name: 'Lissage Japonais', svc_s6_desc: 'Restructuration permanente des liaisons disulfure du cheveu. Résultats soyeux qui repoussent magnifiquement.',
    svc_s7_name: 'Restauration Olaplex', svc_s7_desc: 'Un soin protéiné scientifique qui reconstruit les liaisons rompues de l\'intérieur.',
    svc_s8_name: 'Rajeunissement du Cuir Chevelu', svc_s8_desc: 'Un soin clinique ciblant la santé des follicules, avec infusion de peptides et luminothérapie LED.',
    svc_s9_name: 'Botox', svc_s9_desc: 'Injection précise de neurotoxine par notre spécialiste esthétique certifiée pour lisser les rides et restaurer une expression juvénile. Résultats naturels, jamais figés.',
    svc_s10_name: 'Fillers Lèvres', svc_s10_desc: 'Filler à l\'acide hyaluronique pour des lèvres plus pleines et symétriques. Notre spécialité : le "galbe naturel" — du volume qui semble inné.',
    svc_s11_name: 'Fillers Rides du Sourire', svc_s11_desc: 'Correction des plis nasogéniens et des rides marionnettes avec un filler HA premium. Adoucit les rides profondes tout en conservant le mouvement naturel du visage.',
    svc_s12_name: 'Rhinoplastie PDO sans Chirurgie', svc_s12_desc: 'Alternative à la rhinoplastie chirurgicale avec des fils polydioxanone pour soulever et définir la pointe et le pont nasal. Zéro temps d\'arrêt.',
    svc_s13_name: 'Fillers Fessiers', svc_s13_desc: 'Rehaussement glutéal non chirurgical avec des fillers bio-stimulants. Ajoute du volume et du galbe sans les risques de l\'augmentation chirurgicale.',
    svc_s14_name: 'Traitement Transpiration (Botox)', svc_s14_desc: 'Traitement de l\'hyperhidrose par micro-injections de toxine botulique aux aisselles, paumes ou pieds. Réduction prouvée de la transpiration excessive jusqu\'à 87%.',
    svc_s15_name: 'Facial Golden Glow', svc_s15_desc: 'Micro-infusion à l\'or 24k + microdermabrasion diamant + LED. Notre facial luxe signature pour un éclat incomparable.',
    svc_s16_name: 'HydraFacial MD', svc_s16_desc: 'L\'hydrafacial médical en 6 étapes avec sérums vortex fusion personnalisés pour nettoyage profond, extraction et hydratation.',
    svc_s17_name: 'Soins Visage', svc_s17_desc: 'Un menu de facials ciblés incluant nettoyage profond, anti-âge, éclat et protocoles peau sensible. Chaque soin est entièrement personnalisé selon les besoins de votre peau.',
    svc_s18_name: 'Soins de Rajeunissement Cutané', svc_s18_desc: 'Renouvellement cutané avancé combinant peelings chimiques, micro-needling et thérapie PRP. Améliore considérablement la texture, le teint et la luminosité.',
    svc_s19_name: 'Soins Skincare', svc_s19_desc: 'Protocoles skincare médicaux ciblant l\'acné, l\'hyperpigmentation, la rosacée et le vieillissement prématuré. Inclut photothérapie LED, soins enzymatiques et sérums sur mesure.',
    svc_s20_name: 'Contouring & Sculpture Corporelle', svc_s20_desc: 'Remodelage non invasif par radiofréquence, cavitation ultrasonique et stimulation musculaire EMS. Cible les dépôts graisseux rebelles et raffermit la peau pour une silhouette sculptée.',
    svc_s21_name: 'Lipolyse / Dissolution de Graisse', svc_s21_desc: 'Injections Aqualyx ou Kybella pour dissoudre définitivement les cellules graisseuses localisées au menton, aux joues, abdomen, cuisses et bras. Alternative cliniquement prouvée à la liposuccion.',
    svc_s22_name: 'Perfusions IV', svc_s22_desc: 'Thérapie par perfusion intraveineuse sur mesure délivrant vitamines, minéraux, antioxydants et hydratation directement dans le sang. Protocoles Éclat, Immunité, Énergie, Récupération et Anti-Âge.',
    svc_s23_name: 'Massage Thérapeutique', svc_s23_desc: 'Massage thérapeutique adapté aux besoins de votre corps, du massage sportif deep-tissue à la session relaxante suédoise. Tous les soins utilisent notre mélange signature d\'argan pressé à froid et d\'huile de jasmin.',
    svc_s24_name: 'Massage Pierres Chaudes', svc_s24_desc: 'Pierres de basalte volcanique chauffées à la température idéale, combinées à de l\'huile d\'argan infusée au CBD pour une libération musculaire profonde et une relaxation intense.',
    svc_s25_name: 'Enveloppement Corporel', svc_s25_desc: 'Enveloppement détoxifiant aux algues et minéraux avec gommage corporel exfoliant. Élimine les impuretés, stimule la circulation et laisse la peau immaculément douce.',
    svc_s26_name: 'Extensions de Cils', svc_s26_desc: 'Cils en soie, vison ou volume appliqués individuellement, personnalisés selon la forme de vos yeux et le rendu souhaité. Sets Classic, Hybrid et Mega-Volume disponibles.',
    svc_s27_name: 'Épilation à la Cire', svc_s27_desc: 'Épilation corps entier avec notre formule miel-résine tiède, douce même pour les peaux sensibles. Sourcils, lèvre, aisselles, brésilien et jambes complètes.',
    svc_s28_name: 'Consultations Beauté', svc_s28_desc: 'Une séance privée de 45 minutes avec l\'une de nos spécialistes seniors pour planifier votre parcours beauté complet. Offerte avec toute réservation de soin.',
    svc_cat7: 'Injectables & Traitements Esthétiques',
    svc_s29_name: 'Traitement Éclat & Hyperpigmentation', svc_s29_desc: 'Protocole de dépigmentation avancé ciblant les taches brunes, le teint irrégulier et le mélasma. Combinaison de sérums éclaircissants, d\'agents chimiques et de luminothérapie LED pour un teint lumineux et uniforme.',
    svc_s30_name: 'Filler Lèvres Russe', svc_s30_desc: 'La technique russe emblématique utilisant un filler à l\'acide hyaluronique pour créer un arc de Cupidon défini, des commissures relevées et une projection naturelle — sans surcharge. Idéale pour un résultat velouté et expressif.',
    svc_s31_name: 'Équilibre du Profil — Joues · Menton · Lèvres', svc_s31_desc: 'Traitement d\'harmonie faciale complète par placement stratégique de fillers dermiques sur les pommettes, le menton et les lèvres. Restaure la symétrie du visage et sublime la structure osseuse naturelle pour un profil sculpté et équilibré.',
    svc_s32_name: 'Injections Anti-Rides (Botox)', svc_s32_desc: 'Injections précises de neuromodulateur pour lisser les pattes d\'oie, les rides du front et les rides du lion. Notre spécialiste utilise des techniques de micro-dosage pour un résultat naturel et reposé — jamais figé.',
    svc_s33_name: 'Filler Plis Nasogéniens', svc_s33_desc: 'Injection ciblée d\'acide hyaluronique pour atténuer les rides partant du nez vers les commissures des lèvres. Restaure le volume facial et lisse les plis profonds pour un teint jeune et reposé.',

    // Shop Page
    shop_eyebrow: 'La Boutique',
    shop_title1: 'Boutique', shop_title2: 'Premium',
    shop_sub: 'Essentiels de beauté de luxe, disponibles exclusivement chez Wendy Beauty.',
    shop_bag: 'Panier',
    shop_quick_add: 'Ajouter',
    shop_cat_all: 'Tout',

    // Gallery Page
    gal_eyebrow: 'Transformations Clients',
    gal_title1: 'La', gal_title2: 'Galerie',
    gal_sub: 'Chaque image raconte une histoire de transformation. De vraies clientes, des résultats extraordinaires.',
    gal_before: 'Avant', gal_after: 'Après',

    // Booking Page
    bk_eyebrow: 'Réservation Conciergerie',
    bk_title: 'Réservez Votre', bk_title_italic: 'Séance',
    bk_step0: 'Service', bk_step1: 'Spécialiste', bk_step2: 'Date & Heure', bk_step3: 'Détails', bk_step4: 'Confirmer',
    bk_choose_service: 'Choisissez Votre Service',
    bk_choose_specialist: 'Sélectionnez Votre Spécialiste',
    bk_choose_datetime: 'Choisissez Date & Heure',
    bk_select_date: 'Sélectionner la Date',
    bk_available_times: 'Créneaux Disponibles',
    bk_your_details: 'Vos Coordonnées',
    bk_review: 'Vérifier & Confirmer',
    bk_back: 'Retour', bk_continue: 'Continuer', bk_confirm_btn: 'Confirmer la Réservation',
    bk_your_selection: 'Votre Sélection',
    bk_label_service: 'Service', bk_label_specialist: 'Spécialiste',
    bk_label_date: 'Date', bk_label_time: 'Heure', bk_label_duration: 'Durée',
    bk_label_client: 'Client', bk_label_contact: 'Contact', bk_label_total: 'Total',
    bk_deposit_note: 'Un acompte de 50$ peut être requis pour sécuriser votre rendez-vous. Paiement intégral à la prestation.',
    bk_journey_note: 'Votre voyage commence par la sélection d\'un service.',
    bk_confirmed_title: 'Confirmé',
    bk_confirmed_sub: 'Votre rendez-vous a été réservé. Une confirmation a été envoyée à',
    bk_confirmed_sub2: 'Nous avons hâte de vous accueillir.',
    bk_summary: 'Récapitulatif du Rendez-vous', bk_investment: 'Investissement',
    bk_return_home: 'Retour à l\'Accueil',
    bk_field_name: 'Nom Complet', bk_field_email: 'Adresse Email', bk_field_phone: 'Numéro de Téléphone',
    bk_field_requests: 'Demandes Spéciales',
    bk_ph_name: 'Votre nom complet', bk_ph_email: 'votre@email.com', bk_ph_phone: '+229 000 000 000',
    bk_ph_requests: 'Allergies, préférences ou demandes particulières...',
    bk_svc_hair: 'Cheveux', bk_svc_medspa: 'Med Spa', bk_svc_body: 'Corps', bk_svc_bridal: 'Mariée', bk_svc_lash: 'Cils & Sourcils',
    bk_svc_s1: 'Extensions Obsidian Silk', bk_svc_s2: 'Transformation Kératine',
    bk_svc_s3: 'Facial Golden Glow', bk_svc_s4: 'Consult Botox & Fillers',
    bk_svc_s5: 'Sculpture Corporelle Sovereign', bk_svc_s6: 'Forfait Mariée',
    bk_svc_s7: 'Pose Complète Extensions Cils', bk_svc_s8: 'Coupe & Brushing Précision',
    bk_svc_d1: '3–4 heures', bk_svc_d2: '2h30', bk_svc_d3: '90 min',
    bk_svc_d4: '45 min', bk_svc_d5: '120 min', bk_svc_d6: '5 heures',
    bk_svc_d7: '2 heures', bk_svc_d8: '1 heure',
    bk_sp1_name: 'Wendy Beaumont', bk_sp1_role: 'Fondatrice & Maître Styliste', bk_sp1_spec: 'Extensions & Couleur',
    bk_sp2_name: 'Isabelle Chen', bk_sp2_role: 'Coloriste Senior', bk_sp2_spec: 'Balayage & Kératine',
    bk_sp3_name: 'Maya Torres', bk_sp3_role: 'Spécialiste Med Spa', bk_sp3_spec: 'Soins Visage & Injectables',
    bk_sp4_name: 'Priya Shah', bk_sp4_role: 'Sculpteuse Corporelle', bk_sp4_spec: 'Soins Corps & Massage',

    // About Page
    ab_eyebrow: 'Notre Histoire',
    ab_title: 'Née d\'une', ab_title_italic: 'Vision',
    ab_p1: 'Wendy Beauty Med Spa a été fondée sur une conviction radicale : que chaque personne qui franchit nos portes mérite de se sentir comme la version la plus extraordinaire d\'elle-même.',
    ab_p2: 'En 2011, Wendy Beaumont est revenue de Paris avec une collection de techniques, une philosophie de beauté souveraine et un rêve. Aujourd\'hui, Wendy Beauty a réalisé plus de 2 400 transformations et s\'est imposée comme la destination pour ceux qui n\'exigent que le meilleur.',
    ab_cta: 'Prendre Rendez-vous',
    ab_val_eyebrow: 'Ce Que Nous Défendons',
    ab_val_title: 'Notre', ab_val_title_italic: 'Philosophie',
    ab_v1_title: 'Maîtrise', ab_v1_desc: 'Chaque technicienne suit plus de 300 heures de formation avancée avant de toucher un seul client. Nous n\'acceptons rien de moins que l\'excellence.',
    ab_v2_title: 'Discrétion', ab_v2_desc: 'Notre clientèle comprend certains des visages les plus reconnaissables au monde. La confidentialité n\'est pas un service — c\'est une promesse sacrée.',
    ab_v3_title: 'Intégrité', ab_v3_desc: 'Nous ne recommanderons jamais un service dont vous n\'avez pas besoin. Nos consultations sont honnêtes, complètes et placent vos intérêts en premier.',
    ab_v4_title: 'Innovation', ab_v4_desc: 'Nous sélectionnons uniquement les techniques et produits les plus avancés des marchés mondiaux. Vous recevez les traitements de demain dès aujourd\'hui.',
    ab_stat1_num: '2 400+', ab_stat1_label: 'Transformations',
    ab_stat2_num: '15+', ab_stat2_label: "Ans d'Excellence",
    ab_stat3_num: '98%', ab_stat3_label: 'Fidélité Clientèle',

    // Contact Page
    contact_eyebrow: 'Contactez-nous',
    contact_title: 'Nous', contact_title2: 'Contacter',
    contact_sub: 'Nous serions ravis de vous entendre. Contactez-nous par formulaire, téléphone, ou rendez-nous visite à Cotonou.',
    contact_send_title: 'Envoyer un Message',
    contact_send_btn: 'Envoyer',
    contact_name_label: 'Nom Complet', contact_email_label: 'Adresse Email',
    contact_subject_label: 'Sujet', contact_message_label: 'Message',
    contact_name_ph: 'Votre nom', contact_email_ph: 'votre@email.com',
    contact_subject_ph: 'Comment pouvons-nous vous aider ?', contact_message_ph: 'Parlez-nous de vos objectifs beauté...',
    contact_received_title: 'Message Reçu',
    contact_received_sub: "Merci de nous avoir contactés. Un membre de notre équipe vous répondra dans les 24 heures.",
    contact_find_us: 'Nous Trouver',
    contact_addr_label: 'Adresse', contact_phone_label: 'Téléphone',
    contact_email_info_label: 'Email', contact_hours_label: 'Horaires',
    contact_addr_val: 'Hôtel Mavilla, Lomnava\nCiné Concorde, Cotonou',
    contact_hours_val: 'Lun–Sam : 9h – 20h\nDim : Sur Rendez-vous',
    contact_follow: 'Suivez-nous',

    // Footer
    footer_desc: "Là où l'élégance rencontre la transformation. Services de beauté de luxe à l'Hôtel Mavilla, Lomnava, Ciné Concorde, Cotonou.",
    footer_newsletter: 'Rejoindre le Cercle Privé',
    footer_welcome: 'Bienvenue dans notre sanctuaire.',
    footer_rights: '© 2026 WENDY BEAUTY MED SPA. TOUS DROITS RÉSERVÉS.',
    footer_location: 'HÔTEL MAVILLA, COTONOU, BÉNIN',
    footer_link_services: 'Services', footer_link_gallery: 'Galerie', footer_link_shop: 'Boutique',
    footer_link_about: 'À Propos', footer_link_booking: 'Réservation', footer_link_contact: 'Contact',
    footer_link_privacy: 'Confidentialité', footer_link_terms: 'Conditions',

    // Cart Sidebar
    cart_title: 'Votre Panier', cart_empty: 'Votre panier est vide.',
    cart_checkout: 'Commander', cart_continue: 'Continuer les Achats',
    cart_total: 'Total',

    // Product Modal
    pm_add_btn: 'Ajouter au Panier',
    pm_color: 'Couleur', pm_weight: 'Poids', pm_rating: 'Note',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang][key] ?? translations['en'][key] ?? key;
  const toggleLang = () => setLang(l => l === 'en' ? 'fr' : 'en');
  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}